[package]
name = "adventofcode-2025"
version = "0.1.0"
edition = "2024"
authors = ["Fran√ßois Perron <fperron@gmail.com>"]
description = "Advent of code 2025"
license = "MIT"

[dependencies]
ureq = "3.1.4"
regex = "1.12.2"
itertools = "0.14.0"
num-complex = "0.4.6"
