name: Test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache daily input
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-input-${{ hashFiles('./.input/**') }}
          path: './.input'

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          cache: true

      - name: Lint
        run: |
          cargo clippy -- -Dwarnings

      - name: Format check
        run: |
          cargo fmt --check

      - name: Test
        run: |
          AOC_SESSION=${{ secrets.AOC_SESSION }} cargo test --release --quiet